---
name: Package builder
description: Build instawow packages.
inputs:
  python-version:
    required: false
    default: "3.13"
    description: The Python version to use.
outputs:
  version:
    value: ${{ steps.get-version.outputs.version }}
    description: instawow version.
runs:
  using: composite
  steps:
    - name: Install uv for Python ${{ inputs.python-version }}
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install nox
      run: uv tool install -p ${{ inputs.python-version }} nox
      shell: bash
      env:
        UV_MANAGED_PYTHON: "1"
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: "22"
    - name: Build packages
      run: >-
        nox
        --error-on-missing-interpreters
        --force-python ${{ inputs.python-version }}
        -s build_dists-${{ inputs.python-version }}
      shell: bash
    - name: Get version
      id: get-version
      run: |
        echo "version=$(jq -r '."version"' dist/instawow/.wheel-metadata.json)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: ./dist
        if-no-files-found: error
        include-hidden-files: true
