[tool.briefcase]
project_name = "instawow-gui"
bundle = "org.instawow"
version = "0.1.0"
url = "https://github.com/layday/instawow"
license = "GNU General Public License v3 (GPLv3)"
author = "layday"
author_email = "layday@protonmail.com"

[tool.briefcase.app.instawow-gui-wrapper]
formal_name = "instawow-gui"
description = "GUI for the World of Warcraft add-on manager instawow"
icon = "src/instawow_gui/resources/instawow_gui"
sources = ["src/instawow_gui_wrapper"]
requires = [
  "instawow[gui]",
]

[tool.briefcase.app.instawow-gui-wrapper.macOS]
requires = [
  "std-nslog",
]

[tool.briefcase.app.instawow-gui-wrapper.linux.appimage]
manylinux = "manylinux_2_28"
system_requires = [
  # Needed to compile pycairo wheel
  "cairo-gobject-devel",
  # Needed to compile PyGObject wheel
  "gobject-introspection-devel",
  # Needed to provide GTK
  "gtk3-devel",
  # Dependencies that GTK looks for at runtime, that need to be
  # in the build environment to be picked up by linuxdeploy
  "libcanberra-gtk3",
  "PackageKit-gtk3-module",
  "gvfs-client",
]
linuxdeploy_plugins = [
  "DEPLOY_GTK_VERSION=3 gtk",
  "./linuxdeploy-plugin-zzzinstawowwebkit2gtk.sh",
]

[tool.briefcase.app.instawow-gui-wrapper.linux.flatpak]
finish_arg."filesystem=host" = true
flatpak_runtime = "org.gnome.Platform"
flatpak_runtime_version = "45"
flatpak_sdk = "org.gnome.Sdk"

[tool.briefcase.app.instawow-gui-wrapper.linux.system.debian]
system_requires = [
  # Needed to compile pycairo wheel
  "libcairo2-dev",
  # Needed to compile PyGObject wheel
  "libgirepository1.0-dev",
]
system_runtime_requires = [
  # Needed to provide GTK and its GI bindings
  "gir1.2-gtk-3.0",
  "libgirepository-1.0-1",
  # Dependencies that GTK looks for at runtime
  "libcanberra-gtk3-module",
  # Needed to provide WebKit2 at runtime
  # Note: Debian 11 and Ubuntu 20.04 require gir1.2-webkit2-4.0 instead
  "gir1.2-webkit2-4.1",
]

[tool.briefcase.app.instawow-gui-wrapper.linux.system.rhel]
system_requires = [
  # Needed to compile pycairo wheel
  "cairo-gobject-devel",
  # Needed to compile PyGObject wheel
  "gobject-introspection-devel",
]
system_runtime_requires = [
  # Needed to support Python bindings to GTK
  "gobject-introspection",
  # Needed to provide GTK
  "gtk3",
  # Dependencies that GTK looks for at runtime
  "libcanberra-gtk3",
  # Needed to provide WebKit2 at runtime
  "webkit2gtk3",
]

[tool.briefcase.app.instawow-gui-wrapper.linux.system.suse]
system_requires = [
  # Needed to compile pycairo wheel
  "cairo-devel",
  # Needed to compile PyGObject wheel
  "gobject-introspection-devel",
]
system_runtime_requires = [
  # Needed to provide GTK
  "gtk3",
  # Needed to support Python bindings to GTK
  "gobject-introspection",
  "typelib(Gtk) = 3.0",
  # Dependencies that GTK looks for at runtime
  "libcanberra-gtk3-module",
  # Needed to provide WebKit2 at runtime
  "libwebkit2gtk3",
  "typelib(WebKit2)",
]

[tool.briefcase.app.instawow-gui-wrapper.linux.system.arch]
system_requires = [
  # Needed to compile pycairo wheel
  "cairo",
  # Needed to compile PyGObject wheel
  "gobject-introspection",
  # Runtime dependencies that need to exist so that the
  # Arch package passes final validation.
  # Needed to provide GTK
  "gtk3",
  # Dependencies that GTK looks for at runtime
  "libcanberra",
  # Needed to provide WebKit2
  "webkit2gtk",
]
system_runtime_requires = [
  # Needed to provide GTK
  "gtk3",
  # Needed to provide PyGObject bindings
  "gobject-introspection-runtime",
  # Dependencies that GTK looks for at runtime
  "libcanberra",
  # Needed to provide WebKit2 at runtime
  "webkit2gtk",
]
